config/routes.rb
Rails.application.routes.draw do
  resources :entries

  root 'entries#index'

  get 'blog/index' => 'blog#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :date, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :entry_title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :entry_date %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :entry_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<% @entries.reverse.each do |entry| %>
  <div class="col-md-10 entry">
    <h2><%= entry.title %></h2>
    <h3><%= entry.date %></h3>
    <p><%= entry.content %></p>
    <%= link_to 'Show', entry %> | <%= link_to 'Edit', edit_entry_path(entry) %> | <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

<br>

<%= link_to new_entry_path, class: "btn btn-default" do%>
  <i class="glyphicon glyphicon-plus"></i>
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @entry.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leblog</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Karma|News+Cycle|Pompiere|Raleway" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-5 sidebar">
          <div id="title">
            <h2>The Misadventures of</h2>
            <h1>Louise Dy Quiangco</h1>
            <h3>/ləˈwiːz dēkyäŋkô/</h3>
           </div> <!--end title -->

          <div id="nav">
            <ul class="side_nav">
              <li><a href="#" target=_blank data-toggle="tooltip" data-placement="top" title="You are here">Blog</a></li>
              <li><a href="http://ldqportfolio.bitballoon.com" target=_blank data-toggle="tooltip" data-placement="top" title="Go to Site">Portfolio</a></li>
              <li><a href="https://catcom.herokuapp.com" target=_blank data-toggle="tooltip" data-placement="top" title="Go to Site">Shop</a></li>
              <li><a href="" data-toggle="tooltip" data-placement="top" title="empty">Archive</a></li>
            </ul>
          </div> <!--end side_nav -->

          <div id="about">

            <h3 class="rotate">About</h3>

            <div class="col-sm-12 col-md-6 col-xs-12 about-photos">
              <a href="" data-toggle="tooltip" data-placement="top" title="This me"><img src="http://78.media.tumblr.com/avatar_1930369511a5_64.pnj" alt="portrait"></a>
              <a href="" data-toggle="tooltip" data-placement="top" title="This my cades"><img src="https://www.yourtango.com/sites/default/files/styles/body_image_default/public/large%20%282%29.jpg" alt="cats"></a>
              <a href="" data-toggle="tooltip" data-placement="top" title="This my spiky floof"><img src="https://pbs.twimg.com/profile_images/653874130798776320/fnsMjRjP_400x400.jpg" alt="hedgehog"></a>
            </div> <!--end about-photos -->

            <div class="col-md-4 col-sm-12 hidden-xs about-text">
              <p>
                I'm older than I look<br>
                act younger than my age<br>
                am smarter than I seem<br>
                the rest is on this page
              </p>
            </div> <!--end about-text -->

          </div> <!--end about -->
        </div> <!--end sidebar -->

        <div class="col-md-offset-5 col-md-7 content">
          <%= yield %>
        </div> <!--end content -->
      </div> <!--end row -->

    </div> <!--end container -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap core JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>